# Generated by Django 4.1 on 2022-09-08 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='awsimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='images')),
                ('prediction', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20, null=True)),
                ('prenom', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('contact', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcapteur', models.CharField(max_length=20)),
                ('statut', models.BooleanField(verbose_name=False)),
                ('lat', models.BigIntegerField(null=True)),
                ('lng', models.BigIntegerField(null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApphytoApp.users')),
            ],
        ),
        migrations.CreateModel(
            name='donneestr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField()),
                ('hamb', models.FloatField()),
                ('hsol', models.FloatField()),
                ('teau', models.FloatField(null=True)),
                ('nitr', models.FloatField(null=True)),
                ('phos', models.FloatField(null=True)),
                ('pota', models.FloatField(null=True)),
                ('capteur_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApphytoApp.equipement')),
            ],
        ),
        migrations.CreateModel(
            name='analyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('rslt', models.CharField(max_length=200, null=True)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='images')),
                ('capt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApphytoApp.equipement')),
            ],
        ),
    ]
