# Generated by Django 4.1 on 2022-08-17 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApphytoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcapteur', models.CharField(max_length=20)),
                ('statut', models.BooleanField(verbose_name=False)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApphytoApp.users')),
            ],
        ),
    ]
