# Generated by Django 4.1 on 2022-08-24 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApphytoApp', '0002_equipement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipement',
            old_name='users',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='equipement',
            name='lat',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='lng',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='nom',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='prenom',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='donneestr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField()),
                ('hamb', models.FloatField()),
                ('hsol', models.FloatField()),
                ('teau', models.FloatField(null=True)),
                ('nitr', models.FloatField(null=True)),
                ('phos', models.FloatField(null=True)),
                ('pota', models.FloatField(null=True)),
                ('capteur_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApphytoApp.equipement')),
            ],
        ),
    ]
