# Generated by Django 4.1 on 2022-08-24 16:43

import ApphytoApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApphytoApp', '0003_rename_users_equipement_user_id_equipement_lat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='analyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_analyse', models.DateTimeField(null=True)),
                ('rslt_analyse', models.CharField(max_length=200, null=True)),
                ('sugt_analyse', models.CharField(max_length=200, null=True)),
                ('Image_url', models.ImageField(blank=True, null=True, upload_to=ApphytoApp.models.upload_to)),
                ('capteur_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApphytoApp.equipement')),
            ],
        ),
    ]
