# Generated by Django 4.1 on 2022-08-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApphytoApp', '0003_rename_users_equipement_user_id_equipement_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyse',
            name='date_analyse',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='img_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='rslt_analyse',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='sugt_analyse',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='donneestr',
            name='nitr',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='donneestr',
            name='phos',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='donneestr',
            name='pota',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='donneestr',
            name='teau',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='nom',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='prenom',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
