# Generated by Django 4.1 on 2022-08-28 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApphytoApp', '0004_analyse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='analyse',
        ),
    ]
