# Generated by Django 4.1 on 2022-08-28 18:52

import ApphytoApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApphytoApp', '0005_delete_analyse'),
    ]

    operations = [
        migrations.CreateModel(
            name='analyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('rslt', models.CharField(max_length=200, null=True)),
                ('Image_url', models.ImageField(blank=True, null=True, upload_to=ApphytoApp.models.upload_to)),
                ('capt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApphytoApp.equipement')),
            ],
        ),
    ]
