# Generated by Django 4.1 on 2022-08-29 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApphytoApp', '0008_analyse_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analyse',
            old_name='Image_url',
            new_name='image_url',
        ),
    ]
