# Generated by Django 4.1 on 2022-08-29 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApphytoApp', '0009_rename_image_url_analyse_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyse',
            name='image_url',
        ),
    ]
